######################################################################
# Automatically generated by qmake (2.01a) mié oct 17 11:46:13 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += histogram.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
